### ISSUE TITLE
make:mips-openwrt-linux-gcc: Command not found

### ISSUE THREAD

**Issue by yj1127** [xieyaxiongfly/Atheros_CSI_tool_OpenWRT_UserSpaceApp_src#4]
Hi
Thanks for your tools. I set Openwrt to my router(WNDR3800). And i downloaded Atheros_CSI_tool_openwrt_UserSpaceApp_src on my laptop.
I tried "make" in "sendData" directory.
But, it says that " make:mips-openwrt-linux-gcc: command not found" 

How could i solve this problem?
Thanks for your help.😄

**Comment by xieyaxiongfly** [comment]
You need to set the cross compile environment first before you can compile. 

https://wiki.openwrt.org/doc/devel/crosscompile
