### ISSUE TITLE
CSI and CSI-len always 0

### ISSUE THREAD

**Issue by magienguyen** [xieyaxiongfly/Atheros_CSI_tool_OpenWRT_UserSpaceApp_src#7]
Hello, I am currently working with TP-link TL WDR 4300 to get CSI. I can used sendData and recvCSI to get the information. However, the value of csi and csi_len is always 0. Can you think of any reason for that? Thank you

**Comment by miligithub** [comment]
@magienguyen  Hi, Did you solve the problem? I was using the same device and encountered the same problem.

**Comment by CSIhicham** [comment]
Hi, 

Did you solve the problem? I was using the TL-WR1043ND v1 device and encountered the same problem ?

Thanks,
